config/routes.rb
Rails.application.routes.draw do
  resources :articles
  devise_for :users
  resources :users, only: [:show]
  resources :trucks
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :title, :content, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
end

app/models/city.rb
class City < ApplicationRecord
has_many :trucks
end

app/models/coverage.rb
class Coverage < ApplicationRecord
  has_many :trucks
end

app/models/truck.rb
class Truck < ApplicationRecord
  belongs_to :user
  belongs_to :truck_type
  belongs_to :truck_merchandise
  belongs_to :truck_load
  belongs_to :coverage
  belongs_to :city
end

app/models/truck_load.rb
class TruckLoad < ApplicationRecord
has_many :trucks
end

app/models/truck_merchandise.rb
class TruckMerchandise < ApplicationRecord
end

app/models/truck_type.rb
class TruckType < ApplicationRecord
has_many :trucks
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  has_many :trucks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:user, :shipper, :trucker, :admin]

  before_create :set_default_user
  after_create  :send_welcome_email

  def set_default_user
    self.role = :user
  end

  def avatar_url
    hash = Digest::MD5.hexdigest(email)
    "http://www.gravatar.com/avatar/#{hash}?s=25&d=identicon"
  end

  def username
    self.email.split('@')[0]
  end

  def send_welcome_email
    UserNotifierMailer.welcome_user(self).deliver_now

    ### Background Jobs --> deliver_later
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  ## add parameters/column to Devise
  before_action :add_parameters_to_user, if: :devise_controller?
  before_action :avatar

  
  protected
    def add_parameters_to_user
      devise_parameter_sanitizer.permit(:sign_up, keys: [:role])
      devise_parameter_sanitizer.permit(:account_update, keys: [:role])
    end
    
    def avatar
      @avatar = user_signed_in? ? current_user.avatar_url : nil
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :is_admin?, except: [:index, :show]
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  # GET /articles
  # GET /articles.json
  def index
    @categories = Category.all
    
    if params[:category].blank?
      @articles = Article.all.order(created_at: :desc)
    else
      @category_id = Category.find_by(name: params[:category]).id
      @articles = Article.where(category_id: @category_id).order(created_at: :desc)
    end

  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
    @categories = Category.all
  end

  # GET /articles/1/edit
  def edit
    
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :category_id, :user_id)
    end

    def is_admin?
      unless current_user.admin?
        flash[:alert] = "You don't have permissions"
        redirect_to articles_path
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  
end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :is_user?, except: [:index, :show]
  before_action :set_truck, only: [:show, :edit, :update, :destroy]


  def index
    # @trucks = Truck.all
  end

  def show
    
  end

  def new
    @truck = Truck.new
  end

  def create
    @truck = Truck.new(truck_params)
    @truck.user = current_user

    if @truck.save
      redirect_to articles_path, notice: 'Truck was successfully created.'
    else
      render :new
    end
  end 

  def edit

  end

  def update
    if @truck.update(truck_params)
      redirect_to articles_path, notice: 'Truck was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @truck.destroy
    redirect_to trucks_url, notice: 'Truck was successfully destroyed.'
  end

  private

  def set_truck
    @truck = Truck.find(params[:id])
  end

  
  def truck_params
    params.require(:truck).permit(:user_id, :truck_type_id, :truck_merchandise_id, :truck_load_id, :coverage_id, :city_id, :gps, :available_now, :image, :latitude, :longitude, :price_per_km)
  end

  def is_user?
    unless current_user
      flash[:alert] = "You don't have permissions"
      redirect_to trucks_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :validate_user
  before_action :find_user, only: [:show]
  
  def show
    avatar_url = current_user.avatar_url
    @large_avatar = "#{avatar_url}&s=170"
  end

  private

  def validate_user
    if current_user.id.to_s != params[:id]
      redirect_to root_path
      flash[:alert] = "You don't have permissions."
    end
  end

  def find_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def bootstrap_class_for(flash_type)
    {
      succes: "alert-success",
      error:  "alert-danger",
      alert: "alert-warning",
      notice: "alert-primary"
    }[flash_type.to_sym] || flash_type.to_s
   end
  
  def flash_messages(_opts = {})
    flash.each do |msg_type, message|
      next if msg_type == :form_error
      concat(content_tag(:div, message.html_safe,{
        class: "alert #{bootstrap_class_for(msg_type)} fade in"}) do
        concat content_tag(:button, 'x', class: "close", data: {
          dismiss: 'alert'
        })
        concat message.html_safe
        end)
     end 
     nil
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trucks_helper.rb
module TrucksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_categories.html.erb
<div class="sidebarInner">
  <div class="panel panel-default">
    <div class="panel-heading">Categories</div>
    <div class="panel-body">
      <ul class="list-unstyle categoryList">
        <% @categories.each do |category| %>
        <li>
          <a href="#">
            <%= link_to  articles_path(category: category.name) do %> 
            <%= category.name %> <span class="pull-right"> <%= category.articles.count %>  </span>
            <% end %>
          </a>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true, class: "listing__form") do |form| %>

<% if article.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

  <ul>
    <% article.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="dashboardBoxBg mb30">
  <div class="profileIntro paraMargin">
    <h3>New Article</h3>
    <p>Here you can write your post.</p>
    <div class="row">
      <div class="form-group col-sm-6 col-xs-12">
        <label for="listingTitle">Listing Title</label>
        <%= form.text_field :title, class: "form-control", id: "listingTitle", placeholder: "Listing Title" %>
      </div>
      <div class="form-group col-sm-6 col-xs-12">
        <label for="listingCategory">Category</label>
        <div class="contactSelect">
          <%= form.collection_select(:category_id, Category.all, :id, :name, {prompt: "Choose a category"}, {class: "select-drop"})%>
        </div>
      </div>
      <div class="form-group col-xs-12">
        <label for="discribeTheListing">Discribe the listing</label>
        <%= form.text_area :content, class: "form-control", placeholder: "Discribe the listing" %>
      </div>
    </div>
  </div>
</div>
<div class="form-footer text-center">
  <%= form.button "Submit", value:"Submit Post", class:"btn-submit", data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Sending..." }%>
</div>
<% end %>

app/views/articles/edit.html.erb
<!-- Dashboard breadcrumb section -->
<div class="section dashboard-breadcrumb-section bg-dark">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h2>Edit Post</h2>
        <ol class="breadcrumb">
          <li><a href="index.html">Home</a></li>
          <li><a href="dashboard.html">Dashboard</a></li>
          <li class="active">Edit Post</li>
        </ol>
      </div>
    </div>
  </div>
</div>

<!-- DASHBOARD ORDERS SECTION -->
<section class="clearfix bg-dark listingSection" id="listing-add-edit">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <%= render 'form', article: @article %>
      </div>
    </div>
  </div>
</section>

app/views/articles/index.html.erb
<!-- PAGE TITLE SECTION -->
<section class="clearfix pageTitleSection bg-image"
  style="background-image: url('/assets/background/bg-page-title.jpg');">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="pageTitle">
          <h2>Blog Page</h2>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- BLOG SECTION -->
<section class="clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-xs-12">
        <% if user_signed_in? && current_user.admin? %>
          <div class="form-group mgnBtm0">
          <%= link_to  "New article", new_article_path, class:"btn btn-primary" %>
        <% end %>
        </div>
        <div class="blogInnerWrapper">
          <div class="thumbnail blogInner ">

            <% @articles.each do |article| %>
            <div class="caption">
              <h4><%= time_ago_in_words(article.created_at) %> ago by <a href="#"> <%= article.user.username %> </a></h4>
              <h3><%= link_to article.title, article %></h3>
              <p>
                <% if article.content.length > 250 %>
                <%= truncate(article.content, length: 300) %>
                <%= link_to  "Read more", article %>                
                <% else %>
                <%= article.content %>
                <% end %>

              </p>
              <% if (current_user.admin? && user_signed_in?)  %>
              <h4> <%= link_to  "Edit article", edit_article_path(article) %> </h4>
              <% end %>
            </div>
            <% end %>

          </div>
        </div>
        <div class="paginationCommon blogPagination">
          <nav aria-label="Page navigation">
            <ul class="pagination">
              <li>
                <a href="#" aria-label="Previous">
                  <span aria-hidden="true"><i class="fa fa-angle-left" aria-hidden="true"></i></span>
                </a>
              </li>
              <li class="active"><a href="#">1</a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#">4</a></li>
              <li><a href="#">5</a></li>
              <li>
                <a href="#" aria-label="Next">
                  <span aria-hidden="true"><i class="fa fa-angle-right" aria-hidden="true"></i></span>
                </a>
              </li>
            </ul>
          </nav>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12">

        <%= render "categories" %>
        
        <div class="sidebarInner">
          <div class="panel panel-default">
            <div class="panel-heading">Recent Posts</div>
            <div class="panel-body">
              <ul class="list-unstyle categoryList">
                <li><a href="#">Curabitur scelerisque lacus sit amet.</a></li>
                <li><a href="#">Morbi pretium ipsum ac massa sollicitu.</a></li>
                <li><a href="#">Etiam eget augue et lorem sagittis.</a></li>
                <li><a href="#">Sed mollis tincidunt massa vel egestas.</a></li>
                <li><a href="#">Aliquam semper dolor nec metus alique.</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/articles/new.html.erb
<%= render "layouts/alerts" %>

<!-- Dashboard breadcrumb section -->
<div class="section dashboard-breadcrumb-section bg-dark">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h2>Submit Listings</h2>
        <ol class="breadcrumb">
          <li><a href="index.html">Home</a></li>
          <li><a href="dashboard.html">Dashboard</a></li>
          <li class="active">Submit Listings</li>
        </ol>
      </div>
    </div>
  </div>
</div>

<!-- DASHBOARD ORDERS SECTION -->
<section class="clearfix bg-dark listingSection" id="listing-add-edit">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <%= render 'form', article: @article %>
      </div>
    </div>
  </div>
</section>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/_alerts.html.erb
<div class="alerts text-center">
  <% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>  
  <% elsif flash[:alert] %>
    <div class="alert alert-danger">
      <%= flash[:alert] %>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
      <nav id="menuBar" class="navbar navbar-default lightHeader animated " role="navigation">
        <div class="container">

          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to root_path, class:"navbar-brand" do %>
              <img src="<%= image_path('logo-blue2.png') %>" alt="" width="140" heigth="44">
            <% end %>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav navbar-right">
              <li class="active dropdown singleDrop">
                <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                  aria-expanded="false">home <i class="fa fa-angle-down" aria-hidden="true"></i></!-->
                <ul class="dropdown-menu">
                  <li><a class="active" href="index.html">Home Map</a></li>
                  <li><a class="" href="index-2.html">Home Travel</a></li>
                  <li><a class="" href="index-3.html">Home Automobile</a></li>
                  <li><a class="" href="index-4.html">Home City</a></li>
                </ul>
              </li>
                            <li class=""><%= link_to  "Blog", articles_path %></li>
              <li class=" dropdown singleDrop">
                <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button"
                  aria-haspopup="true" aria-expanded="false">admin <i class="fa fa-angle-down"
                    aria-hidden="true"></i></a>
                <ul class="dropdown-menu">
                  <li><a href="dashboard.html">Dashboard</a></li>
                  <li><a href="add-listings.html">Add Listing</a></li>
                  <li><a href="edit-listings.html">Edit Listing</a></li>
                  <li><a href="booking-list.html">Booking List</a></li>
                  <li><a href="dashboard-reviews.html">Reviews</a></li>
                  <li><a href="listings.html">My Listings</a></li>
                  <li><a href="profile.html">My Profile</a></li>
                  <li><a href="oders.html">My Orders</a></li>
                  <li><a href="sign-up.html">Create Account</a></li>
                  <li><a href="login.html">Login</a></li>
                  <li><a href="index.html">Log Out</a></li>
                </ul>
              </li>
              <%= render 'layouts/user_signed' %>
            </ul>
          </div>
          <% if user_signed_in? %>
            <%= link_to "New Truck", new_truck_path, class:"btn btn-default navbar-btn" %>
          <% end %>
        </div>
      </nav>

app/views/layouts/_user_signed.html.erb
<% if user_signed_in?  %>
  <li class=" dropdown singleDrop">
    <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
      aria-expanded="false"> 
      <img src="<%= @avatar %>" class="img-circle"> 
      <i class="fa fa-angle-down" aria-hidden="true"></i></a>
    <ul class="dropdown-menu">
      <li> <%= link_to  "My profile", current_user %> </li>
      <li> <%= link_to  "Edit user", edit_user_registration_path %> </li>
      <li> <%= link_to  "Logout", destroy_user_session_path, method: :delete %> </li>
    </ul>
  </li>
<% else %>
  <li> <%= link_to  "Login", new_user_session_path %> </li>
  <li> <%= link_to  "Register", new_user_registration_path %> </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>TruckApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDU79W1lu5f6PIiuMqNfT1C6M0e_lq1ECY"></script>

  <!-- GOOGLE FONT -->
  <link href="https://fonts.googleapis.com/css?family=Muli:200,300,400,600,700,800,900" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Herr+Von+Muellerhoff" rel="stylesheet">

</head>

<body id="body" class="body-wrapper boxed-menu">

  <div class="main-wrapper">
    <!-- HEADER -->
    <header id="pageTop" class="header">
      <!-- NAVBAR -->
      <div class="nav-wrapper navbarWhite">
        <!-- TOP INFO BAR -->
        <%= render  "layouts/navbar" %>
  
      </div>
    </header>
    <%= flash_messages %>
    <!-- no tengo contenido aun en home/index -->
    <%= yield %>
  
    <!-- alerts -->
    <script>
      $(".alert").fadeIn(500).css("opacity", "0.85").delay(6000).slideUp(1000);
      $(".alerts").on('click', '.alert', function(){$(this).remove()})
    </script>
      
    <!-- alerts -->
  </div>
<!-- <% if user_signed_in? %>
<%=current_user.email%>
<%= link_to "Logout", destroy_user_session_path, method: :delete %>
<%else%>
<%= link_to "Login", new_user_session_path %>
<% end %> -->
</body>

</html>

app/views/trucks/_form.html.erb
<%= form_with(model: truck, local: true, class: "listing__form") do |form| %>

<% if truck.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(truck.errors.count, "error") %> prohibited this trucj from being saved:</h2>

  <ul>
    <% truck.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="dashboardBoxBg mb30">
  <div class="profileIntro paraMargin">
    <h3>New Truck</h3>
    <p>Here you can create your truck.</p>
    <div class="row">
      
      <div class="form-group col-sm-6 col-xs-12">
        <div class="contactSelect">
          <%= form.collection_select(:truck_type_id, TruckType.all, :id, :name, {prompt: "Choose a truck type"}, {class: "select-drop"})%>
        </div>
      </div>

      <div class="form-group col-sm-6 col-xs-12">
        <div class="contactSelect">
          <%= form.collection_select(:truck_merchandise_id, TruckMerchandise.all, :id, :name, {prompt: "Choose Merchandise"}, {class: "select-drop"})%>
        </div>
      </div>

      <div class="form-group col-sm-6 col-xs-12">
        <div class="contactSelect">
          <%= form.collection_select(:truck_load_id, TruckLoad.all, :id, :name, {prompt: "Choose load"}, {class: "select-drop"})%>
        </div>
      </div>

      <div class="form-group col-sm-6 col-xs-12">
        <div class="contactSelect">
          <%= form.collection_select(:coverage_id, Coverage.all, :id, :name, {prompt: "Choose coverage"}, {class: "select-drop"})%>
        </div>
      </div>

      <div class="form-group col-sm-6 col-xs-12">
        <div class="contactSelect">
          <%= form.collection_select(:city_id, Coverage.all, :id, :name, {prompt: "Choose city"}, {class: "select-drop"})%>
        </div>
      </div>

      <div class="form-group col-sm-6 col-xs-12">
        <div class="contactSelect">
          <label for="">GPS </label>
          <%= form.check_box :gps %>  
        </div>
      </div>

      <div class="form-group col-sm-6 col-xs-12">
        <div class="contactSelect">
          <label for="">Available now </label>
          <%= form.check_box :available_now %>
        </div>
      </div>

      <div class="form-group col-sm-6 col-xs-12">
        <div class="contactSelect">
          <label for="">Latitude </label>
          <%= form.text_field :latitude %>
        </div>
      </div>

      <div class="form-group col-sm-6 col-xs-12">
        <div class="contactSelect">
          <label for="">Longitude </label>
          <%= form.text_field :longitude %>
        </div>
      </div>

      <div class="form-group col-sm-6 col-xs-12">
        <div class="contactSelect">
          <label for="">Price Per Km </label>
          <%= form.text_field :price_per_km %>
        </div>
      </div>
      
    </div>
  </div>
</div>
<div class="form-footer text-center">
  <%= form.button "Submit", value:"Submit Post", class:"btn-submit", data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Sending..." }%>
</div>
<% end %>

app/views/trucks/edit.html.erb
<!-- Dashboard breadcrumb section -->
<div class="section dashboard-breadcrumb-section bg-dark">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h2>Submit Listings</h2>
        <ol class="breadcrumb">
          <li><a href="index.html">Home</a></li>
          <li><a href="dashboard.html">Dashboard</a></li>
          <li class="active">Submit Listings</li>
        </ol>
      </div>
    </div>
  </div>
</div>

<!-- DASHBOARD ORDERS SECTION -->
<section class="clearfix bg-dark listingSection" id="listing-add-edit">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <%= render 'form', truck: @truck %>
      </div>
    </div>
  </div>
</section>

app/views/trucks/index.html.erb
<h1>Index Truck Page</h1>

<% @trucks.each do |truck| %>
<h1><%= truck.latitude %></h1>  
<h4> <%= link_to  "Edit truck", edit_truck_path(truck) %> </h4>
<% end %>

app/views/trucks/new.html.erb
<%= render "layouts/alerts" %>

<!-- Dashboard breadcrumb section -->
<div class="section dashboard-breadcrumb-section bg-dark">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h2>Submit Listings</h2>
        <ol class="breadcrumb">
          <li><a href="index.html">Home</a></li>
          <li><a href="dashboard.html">Dashboard</a></li>
          <li class="active">Submit Listings</li>
        </ol>
      </div>
    </div>
  </div>
</div>

<!-- DASHBOARD ORDERS SECTION -->
<section class="clearfix bg-dark listingSection" id="listing-add-edit">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <%= render 'form', truck: @truck %>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<!-- Dashboard breadcrumb section -->
<div class="section dashboard-breadcrumb-section bg-dark">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h2>My Profile</h2>
        <ol class="breadcrumb">
          <li><a href="index.html">Home</a></li>
          <li><a href="dashboard.html">Dashboard</a></li>
          <li class="active">My Profile</li>
        </ol>
      </div>
    </div>
  </div>
</div>

<!-- DASHBOARD PROFILE SECTION -->
<section class="clearfix bg-dark profileSection">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-sm-5 col-xs-12">
        <div class="dashboardBoxBg mb30">
          <div class="profileImage">
            <img src="<%= @large_avatar %>" alt="Image User" class="img-circle">
            <div class="file-upload profileImageUpload">
              <div class="upload-area">
                <input type="file" name="img[]" class="file">
                <button class="browse" type="button">Upload a Picture <i class="icon-listy icon-upload"></i></button>
              </div>
            </div>
          </div>
          <div class="profileUserInfo bt profileName">
            <p>Your Current Plan</p>
            <h2>Platinum Package</h2>
            <h5>Next Payment: <span>15/01/2017</span></h5>
            <a href="#" class="btn btn-primary">Change</a>
          </div>
        </div>
      </div>
      <div class="col-md-8 col-sm-7 col-xs-12">
        <form>
          <div class="dashboardBoxBg">
            <div class="profileIntro">
              <h2>Your Profile - <%= current_user.username %> </h2>
              <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered
                alteration in some form Ipsum available.</p>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>